# Generated by Django 4.1.7 on 2023-03-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackFusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField()),
                ('email', models.CharField(max_length=40)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
    ]
